name: Jena

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Selecting Jena config
        run: export "config=Jena.properties"

      - name: Run Tests
        run: chmod 755 .github/bin/integration_tests.sh && .github/bin/integration_tests.sh
